### PR TITLE
fixes a race condition and a deadlock in nats sink

### LINKED ISSUE #61: [bug] race condition in nats streaming sink
In rare occurrences the ack callback send to the go channel `natsAcks` (https://github.com/uw-labs/substrate/blob/master/natsstreaming/nats_streaming.go#L122) is observed before the send on the `toAck` channel (https://github.com/uw-labs/substrate/blob/master/natsstreaming/nats_streaming.go#L127). This causes a send of an error on the go channel in line https://github.com/uw-labs/substrate/blob/master/natsstreaming/nats_streaming.go#L90. However, because of the way the loops terminate, this error never becomes observable, as the function never terminates (this is to do with the deferred cancel and waitgroup calls). I'll send an example that fixed this issue locally.

My proposal is that we don't check for these ids lining up. I don't see any practical reason for doing so. I therefore propose removing the go routine at https://github.com/uw-labs/substrate/blob/master/natsstreaming/nats_streaming.go#L82 and just sending the ack confirmation for the message in the callback (closing over it).

### PR DESCRIPTION
**Pull request by thinktainer**
closes #61

### CODE REVIEW

File: natsstreaming/nats_streaming.go [hunk 1]
```diff
@@ -57,80 +56,49 @@ type asyncMessageSink struct {
...
 	natsAckErrs := make(chan error, 1)
-
-	type toAckType struct {
-		guid    string
-		message substrate.Message
-	}
-
-	toAck := make(chan toAckType)
 	ackErrs := make(chan error, 1)
+	publishErr := make(chan error, 1)
```
Comment (SpeedyCoder) [inline natsstreaming/nats_streaming.go]: now the `ackErrs` channel is not used anywhere...

File: natsstreaming/nats_streaming.go [hunk 2]
```diff
@@ -57,80 +56,49 @@ type asyncMessageSink struct {
...
-			//return ctx.Err()
-			return nil
-		case msg := <-messages:
-			guid, err := conn.PublishAsync(p.subject, msg.Data(), func(guid string, err error) {
-				if err != nil {
-					select {
-					case natsAckErrs <- err:
-					default:
+				//return ctx.Err()
+				break LOOP
```
Comment (SpeedyCoder) [inline natsstreaming/nats_streaming.go]: I think it's nicer to just `return` here instead of breaking of the named loop, but that's just my personal preference as I'm not big fan of named loops 😅

Comment (thinktainer) [reply natsstreaming/nats_streaming.go]: It seemed to never return. I agree that it looks ugly, however has served me well so far, and is explicit. I also normally have some tidy up at the bottom of the for loops, so for me that's less I have to remember.

**Comment by thinktainer** [comment]
@mjgarton can i get a second +1 please?
